export const EDIT_FIELD1 = [
  {
    id: uuidv4(),
    label: 'Xưng hô',
    type: 'CRMComboBox',
    tooltipIcon: 'false',
    required: false,
    hasToolTipIcon: false,
    fullToolTipContent: '',
  },
  {
    id: uuidv4(),
    label: 'Tên',
    type: 'text',
    tooltipIcon: false,
    required: true,
    hasToolTipIcon: false,
    fullToolTipContent: '',
  },
  {
    id: uuidv4(),
    label: 'Phòng ban',
    type: 'CRMComboBox',
    tooltipIcon: false,
    required: false,
    hasToolTipIcon: false,
    fullToolTipContent: '',
  },
  {
    id: uuidv4(),
    label: 'ĐT di động',
    type: 'text',
    tooltipIcon: true,
    required: false,
    hasToolTipIcon: true,
    fullToolTipContent: 'Điện thoại di động',
  },
  {
    id: uuidv4(),
    label: 'Email cơ quan',
    type: 'text',
    tooltipIcon: false,
    required: false,
    hasToolTipIcon: false,
    fullToolTipContent: '',
  },
  {
    id: uuidv4(),
    label: 'Mã số thuế',
    type: 'text',
    tooltipIcon: false,
    required: false,
    hasToolTipIcon: false,
    fullToolTipContent: '',
  },
  {
    id: uuidv4(),
    label: 'Nguồn gốc',
    type: 'CRMComboBox',
    tooltipIcon: false,
    required: false,
    hasToolTipIcon: false,
    fullToolTipContent: '',
  },
  {
    id: uuidv4(),
    label: 'Zalo',
    type: 'text',
    tooltipIcon: false,
    required: false,
    hasToolTipIcon: false,
    fullToolTipContent: '',
  },
  {
    id: uuidv4(),
    label: 'Phân loại khách hàng',
    type: 'CRMComboBox',
    tooltipIcon: false,
    required: false,
    hasToolTipIcon: false,
    fullToolTipContent: '',
  },
  {
    id: uuidv4(),
    label: 'Loại học bổng',
    type: 'text',
    tooltipIcon: false,
    required: false,
    hasToolTipIcon: false,
    fullToolTipContent: '',
  },
  {
    id: uuidv4(),
    label: 'Điểm HSKK',
    type: 'text',
    tooltipIcon: false,
    required: false,
    hasToolTipIcon: false,
    fullToolTipContent: '',
  },
  {
    id: uuidv4(),
    label: 'Điểm HSK',
    type: 'text',
    tooltipIcon: false,
    required: false,
    hasToolTipIcon: false,
    fullToolTipContent: '',
  },
  {
    id: uuidv4(),
    label: 'Chia sẻ cá nhân',
    type: 'textArea',
    tooltipIcon: false,
    required: false,
    hasToolTipIcon: false,
    fullToolTipContent: '',
  },
]
