// Thông tin tiềm năng
// const LEAD_DATA = [
//   {
//     LeadID: '148ed882-32b8-218e-9c20-39c2f00615e8',
//     LeadCode: 'TN-6273',
//     LastName: 'Nguy?n',
//     FirstName: 'Th? Ng?c',
//     Email: 'ngkhanh184@gmail.com',
//     Address: ' Y�n Ba�i ',
//     TitleID: '5e6695e2-5aad-3241-6c1a-bb545470e80c',
//     TitleName: ' Truo?ng pho`ng ',
//     AnnualRevenueID: '447816de-6069-15bf-de3d-c9e9e9038fe2',
//     AnnualRevenueName: ' 5 ty? d�`ng ',
//     SalutationID: '1',
//     SalutationName: ' Ba` ',
//     DepartmentID: '1f60e54f-196f-45f3-5498-ae38c5379e4b',
//     DepartmentName: ' Pho`ng truy�`n th�ng',
//     Mobile: '0362734857',
//     OfficeMobile: '0972517213',
//     LeadSourceID: '1',
//     LeadSourceName: 'Kha�ch ha`ng duo?c ta?ng mi�~n phi�',
//     LeadTypeID: '1',
//     LeadTypeName: 'KH Thuong Ma?i',
//     Zalo: 'Mai Thu?n',
//     OfficeEmail: 'lognhat35@gmail.com',
//     CompanyName: ' FPT Soft ',
//     TaxCode: '34460IS0VLEKG',
//     BankAccount: '8234135616',
//     EstablishDay: '23/06/2018 12:00:00 AM',
//     SectorID: '1',
//     SectorName: 'Alternative Energy',
//     BankName: 'Saccombank',
//     BusinessTypeID: '1',
//     BusinessTypeName: 'C�ng ty TNHH',
//     IndustryID: '1',
//     IndustryName: '\r\nDi?ch vu? du li?ch',
//     CountryID: '1',
//     CountryName: 'Vi�?t Nam',
//     DistrictID: '1',
//     DistrictName: 'Huy�?n Phu�c tho?',
//     Street: '16 Ngo~ 225',
//     ProvinceID: '1',
//     ProvinceName: 'null',
//     WardID: '1',
//     WardName: 'Qu�t L�m tu?',
//     ZipCode: '96821',
//     Description:
//       'Ut doloremque iste debitis. Voluptate voluptatem explicabo est et totam. Qui dolorum eaque commodi. Ea eligendi tempora magnam quas; perspiciatis ullam quia.',
//     IsPublic: 'true',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
//   {
//     LeadID: '14ee7bc0-194c-3948-57be-406293204378',
//     LeadCode: 'TN-6525',
//     LastName: 'Nguy?n',
//     FirstName: 'Th? Ly',
//     Email: 'qkhai019gmail.com',
//     Address: ' Nam �i?nh ',
//     TitleID: '11643064-22fb-7e14-1399-04b3a3d51ef2',
//     TitleName: ' Qua?n ly� ',
//     AnnualRevenueID: '1cab3f5f-2daa-759f-e936-63d5d5eff719',
//     AnnualRevenueName: '1 ty? d�`ng ',
//     SalutationID: '14',
//     SalutationName: ' Ba` ',
//     DepartmentID: '26895d47-1420-68d0-9e66-a58ab8ff47ca',
//     DepartmentName: ' Pho`ng da`o ta?o ',
//     Mobile: '0337955274',
//     OfficeMobile: '0976880321',
//     LeadSourceID: '14',
//     LeadSourceName: 'Kha�ch ha`ng tu? ti`m d�n\r\n',
//     LeadTypeID: '14',
//     LeadTypeName: 'KH Thuong Ma?i',
//     Zalo: 'Nguy?n Anh',
//     OfficeEmail: 'dvhoan201@gmail.com',
//     CompanyName: ' Solution Dev ',
//     TaxCode: '5SM19T737FXQW',
//     BankAccount: '6449543231',
//     EstablishDay: '23/09/2015 12:00:00 AM',
//     SectorID: '14',
//     SectorName: 'Forestry & Paper',
//     BankName: 'Agribank',
//     BusinessTypeID: '14',
//     BusinessTypeName: 'Cu?a ha`ng trung t�m',
//     IndustryID: '14',
//     IndustryName: '\r\nDi?ch vu? cung u�ng ph�`n m�`m',
//     CountryID: '14',
//     CountryName: 'Vi�?t Nam',
//     DistrictID: '14',
//     DistrictName: 'Huy�?n Qu��c Oai',
//     Street: '16 Ngo~ 225',
//     ProvinceID: '14',
//     ProvinceName: 'Ha` Nam',
//     WardID: '14',
//     WardName: 'Qu�t L�m tu?',
//     ZipCode: '48685',
//     Description:
//       'Ipsa sit quia. Repellat aut minima? Molestiae sit sunt! Velit iste sapiente. At et voluptatem. Expedita velit sit. Natus dolore temporibus. Sit iure.',
//     IsPublic: 'true',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
//   {
//     LeadID: '15d0d796-1465-4665-fc83-196123975cb2',
//     LeadCode: 'TN-6383',
//     LastName: 'Tr?nh',
//     FirstName: 'Ng?c Ly',
//     Email: 'vthanh0019@gmail.com',
//     Address: ' Ha` Nam ',
//     TitleID: '15b4ab0a-3b8f-6f6f-2a8f-4d82f3a13455',
//     TitleName: ' Qua?n ly� ',
//     AnnualRevenueID: '74b4ef62-677e-21c3-88db-f21ac591aca5',
//     AnnualRevenueName: '1 ty? d�`ng ',
//     SalutationID: '10',
//     SalutationName: ' Anh Chi?',
//     DepartmentID: '114b715b-430f-74cd-d5c6-21b180c0988f',
//     DepartmentName: '\r\n Pho`ng nghi�n cu�u ',
//     Mobile: '0872391095',
//     OfficeMobile: '0972942398',
//     LeadSourceID: '10',
//     LeadSourceName: 'Kha�ch ha`ng duo?c ta?ng mi�~n phi�',
//     LeadTypeID: '10',
//     LeadTypeName: 'KH Thuong Ma?i',
//     Zalo: 'Nguy?n Loan',
//     OfficeEmail: 'yeutien184@gmail.com',
//     CompanyName: '\r\n Theanh28 Express',
//     TaxCode: '57JU4N65GPEQJ',
//     BankAccount: '5678042388',
//     EstablishDay: '31/07/2021 12:00:00 AM',
//     SectorID: '10',
//     SectorName: 'Industrial Engineering',
//     BankName: 'VietComBank',
//     BusinessTypeID: '10',
//     BusinessTypeName: 'T�? chu�c phi chi�nh phu?',
//     IndustryID: '10',
//     IndustryName: '\r\nDi?ch vu? du li?ch',
//     CountryID: '10',
//     CountryName: 'Vi�?t Nam',
//     DistrictID: '10',
//     DistrictName: 'Huy�?n Phu�c tho?',
//     Street: '398 ngo~ ~421',
//     ProvinceID: '10',
//     ProvinceName: 'Ha` Nam',
//     WardID: '10',
//     WardName: 'Qu�t L�m tu?',
//     ZipCode: '67589',
//     Description: 'Aut mollitia ut iure enim voluptatibus in...',
//     IsPublic: 'true',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
//   {
//     LeadID: '1b691e79-236d-5b5a-9d20-39c2f00615e8',
//     LeadCode: 'TN-0280',
//     LastName: 'Nguy?n',
//     FirstName: 'Minh Hi?u',
//     Email: 'thinhutc191204033@gmail.com',
//     Address: ' Phu� Tho? ',
//     TitleID: '11fbda18-5d9f-396c-1299-04b3a3d51ef2',
//     TitleName: 'Gia�m d��c ',
//     AnnualRevenueID: '79aca385-65e3-1ebe-f488-479bce9b28fc',
//     AnnualRevenueName: ' 15 ty? d�`ng ',
//     SalutationID: '5',
//     SalutationName: ' Ba` ',
//     DepartmentID: '6827e1c0-5b98-6d19-831b-27d9d367aeb0',
//     DepartmentName: '\r\n Pho`ng nghi�n cu�u ',
//     Mobile: '0365915651',
//     OfficeMobile: '0367557018',
//     LeadSourceID: '5',
//     LeadSourceName: ' \r\nTh�ng qua h�?i tha?o, t�?p hu�n?',
//     LeadTypeID: '5',
//     LeadTypeName: 'KH Sa?n Xu�t',
//     Zalo: 'Mai Mai',
//     OfficeEmail: 'mtudz35@gmail.com',
//     CompanyName: '\r\n Theanh28 Express',
//     TaxCode: '35H683KO09T5E',
//     BankAccount: '2620801467',
//     EstablishDay: '24/11/2017 12:00:00 AM',
//     SectorID: '5',
//     SectorName: 'Travel & Leisure',
//     BankName: 'VietComBank',
//     BusinessTypeID: '5',
//     BusinessTypeName: 'Cu?a ha`ng trung t�m',
//     IndustryID: '5',
//     IndustryName: '\r\nDi?ch vu? cho thu� ba?o v�? v�? si~',
//     CountryID: '5',
//     CountryName: 'Vi�?t Nam',
//     DistrictID: '5',
//     DistrictName: 'Huy�?n Qu��c Oai',
//     Street: '186 ngo~ ~830',
//     ProvinceID: '5',
//     ProvinceName: 'Nam �i?nh',
//     WardID: '5',
//     WardName: 'Ha` son',
//     ZipCode: '27381',
//     Description:
//       'Eum odit omnis porro perspiciatis ea dolorem. Omnis quas quae quis odio cumque aperiam.',
//     IsPublic: 'false',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
//   {
//     LeadID: '20bbbd0b-3c4a-7d94-6f09-bf1378b8dc91',
//     LeadCode: 'TN-3386',
//     LastName: 'Nguy?n',
//     FirstName: 'Minh Tu?n',
//     Email: 'qkhai019gmail.com',
//     Address: ' Ho`a Bi`nh \r\n',
//     TitleID: '4a0e751e-750e-45c3-de78-cf6d4dd5c4a3',
//     TitleName: ' Nh�n vi�n',
//     AnnualRevenueID: '1944b789-48b3-5241-f588-479bce9b28fc',
//     AnnualRevenueName: '1 ty? d�`ng ',
//     SalutationID: '12',
//     SalutationName: '�ng ',
//     DepartmentID: '3564d2c8-2839-5bf7-851b-27d9d367aeb0',
//     DepartmentName: ' Pho`ng truy�`n th�ng',
//     Mobile: '0971674421',
//     OfficeMobile: '0334675147',
//     LeadSourceID: '12',
//     LeadSourceName: 'Kha�ch ha`ng duo?c ta?ng mi�~n phi�',
//     LeadTypeID: '12',
//     LeadTypeName: 'KH Sa?n Xu�t',
//     Zalo: 'Nguy?n Th�nh',
//     OfficeEmail: 'dgchung2k@gmail.com',
//     CompanyName: ' Solution Dev ',
//     TaxCode: 'K722KA0214FL9',
//     BankAccount: '9379967709',
//     EstablishDay: '01/09/2015 12:00:00 AM',
//     SectorID: '12',
//     SectorName: 'Real Estate Investment & Services',
//     BankName: 'Agribank',
//     BusinessTypeID: '12',
//     BusinessTypeName: 'C�ng ty TNHH',
//     IndustryID: '12',
//     IndustryName: '\r\nDi?ch vu? cho thu� kho ba~i',
//     CountryID: '12',
//     CountryName: 'Vi�?t Nam',
//     DistrictID: '12',
//     DistrictName: 'Huy�?n Phu�c tho?',
//     Street: '802 ngo~ ~820',
//     ProvinceID: '12',
//     ProvinceName: 'Nam �i?nh',
//     WardID: '12',
//     WardName: 'Tru?c Tha�i',
//     ZipCode: '25316',
//     Description:
//       'Dolorum blanditiis ut. Aliquam dolor quasi! Molestiae aperiam et. Natus voluptatem aut! Est nulla omnis? Et delectus veritatis. Perspiciatis voluptatem in!',
//     IsPublic: 'true',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
//   {
//     LeadID: '22f29725-54f0-11f0-9d0b-87ae14180c33',
//     LeadCode: 'TN-1767',
//     LastName: 'Nguy?n',
//     FirstName: 'Mai Loan',
//     Email: 'vhvt297@gmail.com',
//     Address: ' \r\nVi~nh Phu�c ',
//     TitleID: '749718aa-2270-77cc-1444-cfd00e0a9b3b',
//     TitleName: 'Gia�m d��c ',
//     AnnualRevenueID: '4a4c7550-5ee4-1843-e13d-c9e9e9038fe2',
//     AnnualRevenueName: ' 5 ty? d�`ng ',
//     SalutationID: '20',
//     SalutationName: '�ng ',
//     DepartmentID: '2ed98b4b-4f60-6e40-5798-ae38c5379e4b',
//     DepartmentName: '\r\n Pho`ng nghi�n cu�u ',
//     Mobile: '0337138572',
//     OfficeMobile: '0366571478',
//     LeadSourceID: '20',
//     LeadSourceName: '\r\nKha�ch ha`ng hoa?c d��i ta�c gio�i thi�?u',
//     LeadTypeID: '20',
//     LeadTypeName: 'KH Sa?n Xu�t',
//     Zalo: 'Nguy?n Linh',
//     OfficeEmail: 'dngoc27782@gmail.com',
//     CompanyName: '\r\n Theanh28 Express',
//     TaxCode: 'N90IF5L5MOLI1',
//     BankAccount: '8020286963',
//     EstablishDay: '06/07/2012 12:00:00 AM',
//     SectorID: '20',
//     SectorName: 'Real Estate Investment Trusts',
//     BankName: 'VietComBank',
//     BusinessTypeID: '20',
//     BusinessTypeName: 'c�ng ty co� v��n d�`u tu nuo�c ngoa`i',
//     IndustryID: '20',
//     IndustryName: '\r\nDi?ch vu? cung u�ng lao d�?ng va` la`m vi�?c',
//     CountryID: '20',
//     CountryName: 'Vi�?t Nam',
//     DistrictID: '20',
//     DistrictName: 'Huy�?n Phu�c tho?',
//     Street: '16 Ngo~ 225',
//     ProvinceID: '20',
//     ProvinceName: 'Ha` N�?i',
//     WardID: '20',
//     WardName: 'Tru?c Tha�i',
//     ZipCode: '52663',
//     Description:
//       'Consequatur qui omnis. Qui libero sequi. Quas omnis repellat. Odio tenetur accusamus! Dolorem dolores voluptas; aliquid error quia. Illo eos ut! Veritatis.',
//     IsPublic: 'true',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
//   {
//     LeadID: '234d2569-6b1c-720c-9f20-39c2f00615e8',
//     LeadCode: 'TN-7891',
//     LastName: 'Nguy?n',
//     FirstName: 'Vi?t Th�nh',
//     Email: 'mtudz35@gmail.com',
//     Address: ' Ho`a Bi`nh \r\n',
//     TitleID: '7ac8b8cf-6a0d-6fa3-d9b8-94f47731937d',
//     TitleName: ' Qua?n ly� ',
//     AnnualRevenueID: '1ae1fc8d-3cd6-7f4e-a226-71cca92946bf',
//     AnnualRevenueName: '\r\n20 ty? d�`ng ',
//     SalutationID: '24',
//     SalutationName: ' Anh Chi?',
//     DepartmentID: '6123f364-3fd4-3ffe-3e6b-1629b83affd2',
//     DepartmentName: ' Pho`ng da`o ta?o ',
//     Mobile: '0334730228',
//     OfficeMobile: '0362600789',
//     LeadSourceID: '24',
//     LeadSourceName: '\r\nKha�ch ha`ng hoa?c d��i ta�c gio�i thi�?u',
//     LeadTypeID: '24',
//     LeadTypeName: 'KH Sa?n Xu�t',
//     Zalo: 'Nguy?n Hu?ng',
//     OfficeEmail: 'lognhat35@gmail.com',
//     CompanyName: 'MISA JSC ',
//     TaxCode: '70Y19Q5NZ059X',
//     BankAccount: '3511911015',
//     EstablishDay: '08/09/2020 12:00:00 AM',
//     SectorID: '24',
//     SectorName: 'Mining',
//     BankName: 'Saccombank',
//     BusinessTypeID: '24',
//     BusinessTypeName: 'Doanh nghi�?p tu nh�n',
//     IndustryID: '24',
//     IndustryName: '\r\nDi?ch vu? hi�u hi?',
//     CountryID: '24',
//     CountryName: 'Vi�?t Nam',
//     DistrictID: '24',
//     DistrictName: 'Huy�?n Qu��c Oai',
//     Street: '835 ngo~ ~226',
//     ProvinceID: '24',
//     ProvinceName: 'Ha` N�?i',
//     WardID: '24',
//     WardName: 'Ha` son',
//     ZipCode: '91427',
//     Description:
//       'Qui natus autem minima. Optio dolorum ratione omnis ut est quia. Optio ipsa quia tempora et suscipit ea.',
//     IsPublic: 'true',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
//   {
//     LeadID: '2520d168-1494-4217-89d5-ba100c6f7bce',
//     LeadCode: 'TN-3118',
//     LastName: 'L�',
//     FirstName: 'Th? Hoa',
//     Email: 'binh20061956@gmail.com',
//     Address: ' Phu� Tho? ',
//     TitleID: '4b635464-5ee2-2a80-f103-13a65cc92c97',
//     TitleName: ' Truo?ng pho`ng ',
//     AnnualRevenueID: '48c0e033-30af-2811-89db-f21ac591aca5',
//     AnnualRevenueName: '\r\n20 ty? d�`ng ',
//     SalutationID: '23',
//     SalutationName: ' Anh Chi?',
//     DepartmentID: '3a0a7c7d-432b-6cf9-871b-27d9d367aeb0',
//     DepartmentName: 'Pho`ng kinh doanh ',
//     Mobile: '0976341708',
//     OfficeMobile: '0876653581',
//     LeadSourceID: '23',
//     LeadSourceName: ' \r\nTh�ng qua h�?i tha?o, t�?p hu�n?',
//     LeadTypeID: '23',
//     LeadTypeName: 'KH Thuong Ma?i',
//     Zalo: 'Nguy?n Hoa',
//     OfficeEmail: 'qtruong270900@gmail.com',
//     CompanyName: '\r\n Theanh28 Express',
//     TaxCode: 'C0RHN81B54D2Z',
//     BankAccount: '5033048924',
//     EstablishDay: '07/05/2021 12:00:00 AM',
//     SectorID: '23',
//     SectorName: 'Tobacco',
//     BankName: 'Agribank',
//     BusinessTypeID: '23',
//     BusinessTypeName: 'C�ng ty TNHH',
//     IndustryID: '23',
//     IndustryName: '\r\nDi?ch vu? cho thu� ba?o v�? v�? si~',
//     CountryID: '23',
//     CountryName: 'Vi�?t Nam',
//     DistrictID: '23',
//     DistrictName: 'Huy�?n Phu�c tho?',
//     Street: '16 Ngo~ 225',
//     ProvinceID: '23',
//     ProvinceName: 'Nam �i?nh',
//     WardID: '23',
//     WardName: 'Ha` son',
//     ZipCode: '22638',
//     Description:
//       'Similique porro consequuntur. Sequi architecto quasi; nisi et aut; reprehenderit magni quaerat. Voluptatem deserunt aut. Eos eum ullam! Inventore dolorum.',
//     IsPublic: 'true',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
//   {
//     LeadID: '25c6c36e-1668-7d10-6e09-bf1378b8dc91',
//     LeadCode: 'TN-6490',
//     LastName: 'Ho�ng',
//     FirstName: 'Ng?c Di?m',
//     Email: 'null',
//     Address: 'null',
//     TitleID: '6207a9a7-3bf9-7288-8565-390639088226',
//     TitleName: 'null',
//     AnnualRevenueID: '3541ff76-58f0-6d1a-e836-63d5d5eff719',
//     AnnualRevenueName: 'null',
//     SalutationID: '2',
//     SalutationName: 'null',
//     DepartmentID: '13a507d0-342d-6292-6de3-2ceaa9cf3765',
//     DepartmentName: 'null',
//     Mobile: 'null',
//     OfficeMobile: '0975579496',
//     LeadSourceID: '2',
//     LeadSourceName: 'null',
//     LeadTypeID: '2',
//     LeadTypeName: 'KH Sa?n Xu�t',
//     Zalo: '�a?ng H�n',
//     OfficeEmail: 'nhungkiuu01@gmail.com',
//     CompanyName: 'null',
//     TaxCode: '8D7W4ME0103K2',
//     BankAccount: '9939982060',
//     EstablishDay: 'null',
//     SectorID: '2',
//     SectorName: 'null',
//     BankName: 'null',
//     BusinessTypeID: '2',
//     BusinessTypeName: 'c�ng ty co� v��n d�`u tu nuo�c ngoa`i',
//     IndustryID: '2',
//     IndustryName: '\r\nDi?ch vu? hi�u hi?',
//     CountryID: '2',
//     CountryName: 'null',
//     DistrictID: '2',
//     DistrictName: 'null',
//     Street: '213 ngo~ ~561',
//     ProvinceID: '2',
//     ProvinceName: 'Ninh Bi`nh',
//     WardID: '2',
//     WardName: 'Ha` son',
//     ZipCode: 'null',
//     Description: 'null',
//     IsPublic: 'null',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
//   {
//     LeadID: '2ea8deee-1b95-2a51-88d5-ba100c6f7bce',
//     LeadCode: 'TN-6613',
//     LastName: 'N�ng',
//     FirstName: 'Th? L?',
//     Email: 'ngthinh949@gmail.com',
//     Address: ' Ha` N�?i',
//     TitleID: '33c6f0f4-3591-2c8e-1244-cfd00e0a9b3b',
//     TitleName: ' Nh�n vi�n',
//     AnnualRevenueID: '73612d31-3ee3-7447-8e7d-817a123d365d',
//     AnnualRevenueName: '\r\n20 ty? d�`ng ',
//     SalutationID: '13',
//     SalutationName: ' Ba` ',
//     DepartmentID: '7fa72f44-2825-2b26-d190-152dfadf6d0d',
//     DepartmentName: ' Pho`ng nh�n su? ',
//     Mobile: '0365638643',
//     OfficeMobile: 'null',
//     LeadSourceID: '13',
//     LeadSourceName: 'Kha�ch ha`ng tu? ti`m d�n\r\n',
//     LeadTypeID: '13',
//     LeadTypeName: 'null',
//     Zalo: 'null',
//     OfficeEmail: 'null',
//     CompanyName: '\r\n Theanh28 Express',
//     TaxCode: '47C3QR5BVP827',
//     BankAccount: '0054104826',
//     EstablishDay: '21/07/2022 12:00:00 AM',
//     SectorID: '13',
//     SectorName: 'null',
//     BankName: 'VietComBank',
//     BusinessTypeID: '13',
//     BusinessTypeName: 'Cu?a ha`ng trung t�m',
//     IndustryID: '13',
//     IndustryName: 'null',
//     CountryID: '13',
//     CountryName: 'Vi�?t Nam',
//     DistrictID: '13',
//     DistrictName: 'Huy�?n Qu��c Oai',
//     Street: 'null',
//     ProvinceID: '13',
//     ProvinceName: 'Ninh Bi`nh',
//     WardID: '13',
//     WardName: 'Ha` son',
//     ZipCode: '75243',
//     Description:
//       'Esse itaque suscipit. Adipisci qui odio? Perspiciatis non eligendi! Necessitatibus eligendi repudiandae; deserunt sint possimus; neque in qui. Vel molestias!',
//     IsPublic: 'true',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
//   {
//     LeadID: '354f1b13-17bf-1b52-87d5-ba100c6f7bce',
//     LeadCode: 'TN-4637',
//     LastName: 'Nguy?n',
//     FirstName: 'Th? Hu?ng',
//     Email: 'phthan247@gmail.com',
//     Address: ' \r\nVi~nh Phu�c ',
//     TitleID: '60e226cb-63fb-4363-fc4d-8601bf3d85d8',
//     TitleName: ' Truo?ng pho`ng ',
//     AnnualRevenueID: '39446ba3-3071-7af6-a5a9-deaf32c96293',
//     AnnualRevenueName: '\r\n20 ty? d�`ng ',
//     SalutationID: '4',
//     SalutationName: ' Anh Chi?',
//     DepartmentID: '3650c04e-62b1-6908-5598-ae38c5379e4b',
//     DepartmentName: ' Pho`ng truy�`n th�ng',
//     Mobile: '0332681204',
//     OfficeMobile: 'null',
//     LeadSourceID: '4',
//     LeadSourceName: 'Kha�ch ha`ng tu? ti`m d�n\r\n',
//     LeadTypeID: '4',
//     LeadTypeName: 'null',
//     Zalo: 'null',
//     OfficeEmail: 'null',
//     CompanyName: 'MISA JSC ',
//     TaxCode: '073M6S4N66X09',
//     BankAccount: '5119796299',
//     EstablishDay: '25/08/2021 12:00:00 AM',
//     SectorID: '4',
//     SectorName: 'Support Services',
//     BankName: 'Agribank',
//     BusinessTypeID: '4',
//     BusinessTypeName: 'Cu?a ha`ng trung t�m',
//     IndustryID: '4',
//     IndustryName: 'null',
//     CountryID: '4',
//     CountryName: 'Vi�?t Nam',
//     DistrictID: '4',
//     DistrictName: 'Huy�?n Qu��c Oai',
//     Street: 'null',
//     ProvinceID: '4',
//     ProvinceName: 'Ninh Bi`nh',
//     WardID: '4',
//     WardName: 'Tru?c Tha�i',
//     ZipCode: '91981',
//     Description:
//       'Dicta voluptas et non nam quo molestiae. Atque accusamus sit error ab sapiente! Doloribus sit labore ratione.',
//     IsPublic: 'false',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
//   {
//     LeadID: '357d7c4e-4b7f-11c2-84c0-08fd2f807219',
//     LeadCode: 'TN-2264',
//     LastName: 'N�ng',
//     FirstName: 'Vi?t Anh',
//     Email: 'dvthanh019@gmail.com',
//     Address: ' Ho`a Bi`nh \r\n',
//     TitleID: '75de26bb-5a5c-467f-2c8f-4d82f3a13455',
//     TitleName: ' Nh�n vi�n',
//     AnnualRevenueID: '61608d17-702d-61ca-f688-479bce9b28fc',
//     AnnualRevenueName: ' 5 ty? d�`ng ',
//     SalutationID: '19',
//     SalutationName: ' Ba` ',
//     DepartmentID: '25a1ce30-4ae1-2133-9f66-a58ab8ff47ca',
//     DepartmentName: ' Pho`ng truy�`n th�ng',
//     Mobile: '0364742578',
//     OfficeMobile: '0337305926',
//     LeadSourceID: '19',
//     LeadSourceName: ' \r\nTh�ng qua h�?i tha?o, t�?p hu�n?',
//     LeadTypeID: '19',
//     LeadTypeName: 'KH Sa?n Xu�t',
//     Zalo: 'Mai Huong',
//     OfficeEmail: 'vthanh0019@gmail.com',
//     CompanyName: ' FPT Soft ',
//     TaxCode: 'E9N92B9513H0Q',
//     BankAccount: '0303860007',
//     EstablishDay: '05/01/2021 12:00:00 AM',
//     SectorID: '19',
//     SectorName: 'Oil & Gas Producers',
//     BankName: 'Agribank',
//     BusinessTypeID: '19',
//     BusinessTypeName: 'Doanh nghi�?p tu nh�n',
//     IndustryID: '19',
//     IndustryName: '\r\nDi?ch vu? cho thu� kho ba~i',
//     CountryID: '19',
//     CountryName: 'Vi�?t Nam',
//     DistrictID: '19',
//     DistrictName: 'Huy�?n Phu�c tho?',
//     Street: '16 Ngo~ 225',
//     ProvinceID: '19',
//     ProvinceName: 'Nam �i?nh',
//     WardID: '19',
//     WardName: 'Non Bi`nh',
//     ZipCode: '51365',
//     Description: 'Ad enim iste quis voluptas aut quia.',
//     IsPublic: 'true',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
//   {
//     LeadID: '36104b10-705b-57a8-83c0-08fd2f807219',
//     LeadCode: 'TN-4094',
//     LastName: 'Nguy?n',
//     FirstName: 'Ng?c Hoa',
//     Email: 'qtruong270900@gmail.com',
//     Address: ' Phu� Tho? ',
//     TitleID: '4bfe55ba-57df-274c-1144-cfd00e0a9b3b',
//     TitleName: 'Gia�m d��c ',
//     AnnualRevenueID: '2102924a-510c-7251-a026-71cca92946bf',
//     AnnualRevenueName: ' 35 ty? d�`ng ',
//     SalutationID: '9',
//     SalutationName: ' Anh Chi?',
//     DepartmentID: '1242d680-4f02-3bbb-9d66-a58ab8ff47ca',
//     DepartmentName: ' Pho`ng da`o ta?o ',
//     Mobile: '0878338096',
//     OfficeMobile: '0873219996',
//     LeadSourceID: '9',
//     LeadSourceName: 'Kha�ch ha`ng tu? ti`m d�n\r\n',
//     LeadTypeID: '9',
//     LeadTypeName: 'KH Sa?n Xu�t',
//     Zalo: 'Tr�n Hu?ng',
//     OfficeEmail: 'binh20061956@gmail.com',
//     CompanyName: 'MISA JSC ',
//     TaxCode: 'TED9PLO9LBEA3',
//     BankAccount: '4695749100',
//     EstablishDay: '02/07/2021 12:00:00 AM',
//     SectorID: '9',
//     SectorName: 'Life Insurance',
//     BankName: 'Saccombank',
//     BusinessTypeID: '9',
//     BusinessTypeName: 'c�ng ty co� v��n d�`u tu nuo�c ngoa`i',
//     IndustryID: '9',
//     IndustryName: '\r\nDi?ch vu? hi�u hi?',
//     CountryID: '9',
//     CountryName: 'Vi�?t Nam',
//     DistrictID: '9',
//     DistrictName: 'Huy�?n Qu��c Oai',
//     Street: '16 Ngo~ 225',
//     ProvinceID: '9',
//     ProvinceName: 'Ha` Nam',
//     WardID: '9',
//     WardName: 'Qu�t L�m tu?',
//     ZipCode: '98918',
//     Description:
//       'Et aperiam quis error. Et illum ut non qui harum. Quod et unde explicabo quia itaque; in commodi omnis sunt aliquid officiis et.',
//     IsPublic: 'false',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
//   {
//     LeadID: '3700cc49-55b5-69ea-4929-a2925c0f334d',
//     LeadCode: 'TN-8127',
//     LastName: 'Tr?nh',
//     FirstName: 'Tu?n Ng?c',
//     Email: 'dngoc27782@gmail.com',
//     Address: ' Vi~nh Phu�c ',
//     TitleID: '6d81a322-63f0-7270-6d1a-bb545470e80c',
//     TitleName: ' Nh�n vi�n',
//     AnnualRevenueID: 'null',
//     AnnualRevenueName: '',
//     SalutationID: '3',
//     SalutationName: ' Ba` ',
//     DepartmentID: '6e0dc48e-3eac-6143-9b66-a58ab8ff47ca',
//     DepartmentName: 'Pho`ng kinh doanh ',
//     Mobile: '0362781584',
//     OfficeMobile: '0367144238',
//     LeadSourceID: '3',
//     LeadSourceName: 'Kha�ch ha`ng tu? ti`m d�n\r\n',
//     LeadTypeID: '3',
//     LeadTypeName: 'KH Sa?n Xu�t',
//     Zalo: 'Tr?nh Ng?c',
//     OfficeEmail: 'qghung19@gmail.com',
//     CompanyName: ' FPT Soft ',
//     TaxCode: 'null',
//     BankAccount: '9527075258',
//     EstablishDay: '11/03/2021 12:00:00 AM',
//     SectorID: '3',
//     SectorName: 'Equity Investment Instruments',
//     BankName: 'Saccombank',
//     BusinessTypeID: '3',
//     BusinessTypeName: 'null',
//     IndustryID: '3',
//     IndustryName: 'Di?ch vu? cham so�c sa�c de?p',
//     CountryID: '3',
//     CountryName: 'Vi�?t Nam',
//     DistrictID: '3',
//     DistrictName: 'Huy�?n Phu�c tho?',
//     Street: '16 Ngo~ 225',
//     ProvinceID: '3',
//     ProvinceName: 'Ha` N�?i',
//     WardID: '3',
//     WardName: 'Ha` son',
//     ZipCode: '12831',
//     Description:
//       'Aliquid aliquam vero reprehenderit voluptatem inventore. Voluptatem pariatur commodi. Quo nam et ipsa et est et.',
//     IsPublic: 'false',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
//   {
//     LeadID: '37dd9bb0-4c53-4134-31de-23e177779933',
//     LeadCode: 'TN-9956',
//     LastName: 'Nguy?n',
//     FirstName: 'Th? Linh',
//     Email: 'thinhutc191204033@gmail.com',
//     Address: ' Phu� Tho? ',
//     TitleID: '697be7ba-1738-6adf-298f-4d82f3a13455',
//     TitleName: ' Qua?n ly� ',
//     AnnualRevenueID: '48b51439-3625-6c0c-7532-03c92da59c43',
//     AnnualRevenueName: ' 30 ty? d�`ng ',
//     SalutationID: '8',
//     SalutationName: '�ng ',
//     DepartmentID: '47782bc9-1bf1-7c7b-6ee3-2ceaa9cf3765',
//     DepartmentName: ' Pho`ng nh�n su? ',
//     Mobile: '0364335423',
//     OfficeMobile: '0970920805',
//     LeadSourceID: '8',
//     LeadSourceName: 'Kha�ch ha`ng tu? ti`m d�n\r\n',
//     LeadTypeID: '8',
//     LeadTypeName: 'KH Thuong Ma?i',
//     Zalo: 'Nguy?n Ho�ng',
//     OfficeEmail: 'vhoa21785@gmail.com',
//     CompanyName: ' Solution Dev ',
//     TaxCode: '363QQ8G1A5OSK',
//     BankAccount: '8047394740',
//     EstablishDay: '13/08/2013 12:00:00 AM',
//     SectorID: '8',
//     SectorName: 'Software & Computer Services',
//     BankName: 'Agribank',
//     BusinessTypeID: '8',
//     BusinessTypeName: 'T�? chu�c phi chi�nh phu?',
//     IndustryID: '8',
//     IndustryName: 'Di?ch vu? cham so�c sa�c de?p',
//     CountryID: '8',
//     CountryName: 'Vi�?t Nam',
//     DistrictID: '8',
//     DistrictName: 'Huy�?n Qu��c Oai',
//     Street: '16 Ngo~ 225',
//     ProvinceID: '8',
//     ProvinceName: 'Ninh Bi`nh',
//     WardID: '8',
//     WardName: 'null',
//     ZipCode: '27438',
//     Description:
//       'Qui optio veritatis. Corporis labore in. Accusantium omnis itaque! Ea est itaque. Officiis est perspiciatis! Recusandae quia quasi. Quas eveniet minus.',
//     IsPublic: 'false',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
//   {
//     LeadID: '38528581-656f-2902-32de-23e177779933',
//     LeadCode: 'TN-8820',
//     LastName: 'L�',
//     FirstName: 'Tu?n M?nh',
//     Email: 'null',
//     Address: 'null',
//     TitleID: '7de0e887-6ace-4435-1344-cfd00e0a9b3b',
//     TitleName: 'null',
//     AnnualRevenueID: '153105e0-6702-29ed-7632-03c92da59c43',
//     AnnualRevenueName: 'null',
//     SalutationID: '17',
//     SalutationName: 'null',
//     DepartmentID: '3800012e-758c-1328-861b-27d9d367aeb0',
//     DepartmentName: 'null',
//     Mobile: 'null',
//     OfficeMobile: '0873301905',
//     LeadSourceID: '17',
//     LeadSourceName: 'null',
//     LeadTypeID: '17',
//     LeadTypeName: 'KH Sa?n Xu�t',
//     Zalo: 'Nguy?n Hoa',
//     OfficeEmail: 'binh20061956@gmail.com',
//     CompanyName: 'null',
//     TaxCode: '5P11396XC9L56',
//     BankAccount: '1983464092',
//     EstablishDay: 'null',
//     SectorID: '17',
//     SectorName: 'null',
//     BankName: 'null',
//     BusinessTypeID: '17',
//     BusinessTypeName: 'Doanh nghi�?p tu nh�n',
//     IndustryID: '17',
//     IndustryName: '\r\nDi?ch vu? cung u�ng lao d�?ng va` la`m vi�?c',
//     CountryID: '17',
//     CountryName: 'null',
//     DistrictID: '17',
//     DistrictName: 'null',
//     Street: '229 ngo~ ~080',
//     ProvinceID: '17',
//     ProvinceName: 'Nam �i?nh',
//     WardID: '17',
//     WardName: 'Qu�t L�m tu?',
//     ZipCode: 'null',
//     Description: 'null',
//     IsPublic: 'null',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
//   {
//     LeadID: '3b86d2ed-446c-5fce-56be-406293204378',
//     LeadCode: 'TN-5187',
//     LastName: 'Nguy?n',
//     FirstName: 'Ng?c Ng?c',
//     Email: 'binh20061956@gmail.com',
//     Address: 'Ninh Bi`nh ',
//     TitleID: '76598eb0-20b1-664e-8665-390639088226',
//     TitleName: ' Qua?n ly� ',
//     AnnualRevenueID: '71952621-23c8-61d2-d0eb-e423f1575e00',
//     AnnualRevenueName: ' 10 ty? d�`ng ',
//     SalutationID: '6',
//     SalutationName: '�ng ',
//     DepartmentID: '1949dae3-4d44-217e-9c66-a58ab8ff47ca',
//     DepartmentName: '\r\n Pho`ng nghi�n cu�u ',
//     Mobile: '0877616409',
//     OfficeMobile: '0362323932',
//     LeadSourceID: '6',
//     LeadSourceName: ' \r\nTh�ng qua h�?i tha?o, t�?p hu�n?',
//     LeadTypeID: '6',
//     LeadTypeName: 'KH Sa?n Xu�t',
//     Zalo: 'Nguy?n Giang',
//     OfficeEmail: 'ngthinh949@gmail.com',
//     CompanyName: 'MISA JSC ',
//     TaxCode: '42W1J985SKW93',
//     BankAccount: '2684098265',
//     EstablishDay: '28/02/2013 12:00:00 AM',
//     SectorID: '6',
//     SectorName: 'Household Goods & Home Construction',
//     BankName: 'VietComBank',
//     BusinessTypeID: '6',
//     BusinessTypeName: 'c�ng ty co� v��n d�`u tu nuo�c ngoa`i',
//     IndustryID: '6',
//     IndustryName: '\r\nDi?ch vu? cho thu� kho ba~i',
//     CountryID: '6',
//     CountryName: 'Vi�?t Nam',
//     DistrictID: '6',
//     DistrictName: 'Huy�?n Qu��c Oai',
//     Street: '518 ngo~ ~846',
//     ProvinceID: '6',
//     ProvinceName: 'Ha` Nam',
//     WardID: '6',
//     WardName: 'Tru?c Tha�i',
//     ZipCode: '15938',
//     Description:
//       'Dicta voluptatem nihil. Eligendi perspiciatis sunt; aperiam facilis atque. Accusantium tempore ut; atque aut quaerat. Natus necessitatibus tenetur. Sed.',
//     IsPublic: 'true',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
//   {
//     LeadID: '4a4a8c90-2e57-215e-58be-406293204378',
//     LeadCode: 'TN-3696',
//     LastName: 'Tr�n',
//     FirstName: 'Tu?n Tru?ng',
//     Email: 'phthan247@gmail.com',
//     Address: ' Nam �i?nh ',
//     TitleID: '4e3e50b0-55de-5c2f-2d8f-4d82f3a13455',
//     TitleName: 'Gia�m d��c ',
//     AnnualRevenueID: '527894c4-1c83-7d9e-f788-479bce9b28fc',
//     AnnualRevenueName: ' 10 ty? d�`ng ',
//     SalutationID: '21',
//     SalutationName: '�ng ',
//     DepartmentID: '3d5b1131-38b5-2128-ebdb-93dede770727',
//     DepartmentName: ' Pho`ng da`o ta?o ',
//     Mobile: '0879409683',
//     OfficeMobile: '0973077664',
//     LeadSourceID: '21',
//     LeadSourceName: '\r\nKha�ch ha`ng hoa?c d��i ta�c gio�i thi�?u',
//     LeadTypeID: '21',
//     LeadTypeName: 'KH Thuong Ma?i',
//     Zalo: 'Nguy?n Anh',
//     OfficeEmail: 'vhoa21785@gmail.com',
//     CompanyName: ' FPT Soft ',
//     TaxCode: 'P3KW0LHPW5T15',
//     BankAccount: '1689778934',
//     EstablishDay: '03/01/2021 12:00:00 AM',
//     SectorID: '21',
//     SectorName: 'null',
//     BankName: 'Saccombank',
//     BusinessTypeID: '21',
//     BusinessTypeName: 'c�ng ty co� v��n d�`u tu nuo�c ngoa`i',
//     IndustryID: '21',
//     IndustryName: '\r\nDi?ch vu? du li?ch',
//     CountryID: '21',
//     CountryName: 'Vi�?t Nam',
//     DistrictID: '21',
//     DistrictName: 'Huy�?n Phu�c tho?',
//     Street: '684 ngo~ ~799',
//     ProvinceID: '21',
//     ProvinceName: 'Ha` Nam',
//     WardID: '21',
//     WardName: 'Tru?c Tha�i',
//     ZipCode: '73979',
//     Description:
//       'Quia commodi laudantium. Non repudiandae odit! Cum vel quisquam. Vitae deserunt autem! Quasi sint corrupti. Natus eligendi culpa; maxime id et. Doloribus.',
//     IsPublic: 'false',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
//   {
//     LeadID: '53baae5e-52f2-2642-4a29-a2925c0f334d',
//     LeadCode: 'TN-6752',
//     LastName: 'Nguy?n',
//     FirstName: 'Tu?n Tru?ng',
//     Email: 'ngthinh949@gmail.com',
//     Address: ' Ba�c Giang ',
//     TitleID: '6ed2e962-178c-712c-fd4d-8601bf3d85d8',
//     TitleName: ' Truo?ng pho`ng ',
//     AnnualRevenueID: '174ffc6c-4080-4bc3-a126-71cca92946bf',
//     AnnualRevenueName: ' 25 ty? d�`ng ',
//     SalutationID: '11',
//     SalutationName: ' Anh Chi?',
//     DepartmentID: '234be17d-3820-7daa-5698-ae38c5379e4b',
//     DepartmentName: ' Pho`ng truy�`n th�ng',
//     Mobile: '0978869654',
//     OfficeMobile: '0978331303',
//     LeadSourceID: '11',
//     LeadSourceName: '\r\nKha�ch ha`ng hoa?c d��i ta�c gio�i thi�?u',
//     LeadTypeID: '11',
//     LeadTypeName: 'KH Sa?n Xu�t',
//     Zalo: 'Tr�n L?',
//     OfficeEmail: 'kakhanh111@gmail.com',
//     CompanyName: ' FPT Soft ',
//     TaxCode: '32M6AUG6JEB27',
//     BankAccount: '3280278560',
//     EstablishDay: '16/06/2022 12:00:00 AM',
//     SectorID: '11',
//     SectorName: 'Nonlife Insurance',
//     BankName: 'Agribank',
//     BusinessTypeID: '11',
//     BusinessTypeName: 'Doanh nghi�?p tu nh�n',
//     IndustryID: '11',
//     IndustryName: '\r\nDi?ch vu? cung u�ng ph�`n m�`m',
//     CountryID: '11',
//     CountryName: 'Vi�?t Nam',
//     DistrictID: '11',
//     DistrictName: 'Huy�?n Phu�c tho?',
//     Street: '16 Ngo~ 225',
//     ProvinceID: '11',
//     ProvinceName: 'Ha` Nam',
//     WardID: '11',
//     WardName: 'Tru?c Tha�i',
//     ZipCode: '60676',
//     Description:
//       'Neque impedit perspiciatis autem. Aperiam ut ullam. Ut aut animi et nisi! Quos vero error sed et nemo ab.',
//     IsPublic: 'true',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
//   {
//     LeadID: '57a3f48f-1c1d-1f04-9e20-39c2f00615e8',
//     LeadCode: 'TN-3938',
//     LastName: 'Ho�ng',
//     FirstName: 'Minh M?nh',
//     Email: 'ngthinh949@gmail.com',
//     Address: ' Vi~nh Phu�c ',
//     TitleID: '30d623f2-31cf-5d4c-f7c3-4d1f326d5ebd',
//     TitleName: ' Nh�n vi�n',
//     AnnualRevenueID: '67f532a4-1158-2919-d1eb-e423f1575e00',
//     AnnualRevenueName: '\r\n20 ty? d�`ng ',
//     SalutationID: '16',
//     SalutationName: ' Ba` ',
//     DepartmentID: '4c411322-7cb4-657d-6fe3-2ceaa9cf3765',
//     DepartmentName: '\r\n Pho`ng nghi�n cu�u ',
//     Mobile: '0979985934',
//     OfficeMobile: '0972102276',
//     LeadSourceID: '16',
//     LeadSourceName: 'Nh�n vi�n kinh doanh tu? ti`m ki�m',
//     LeadTypeID: '16',
//     LeadTypeName: 'KH Thuong Ma?i',
//     Zalo: 'B�i Tru?ng',
//     OfficeEmail: 'dvhoan201@gmail.com',
//     CompanyName: 'MISA JSC ',
//     TaxCode: 'HCW5CAW016J40',
//     BankAccount: '6782491575',
//     EstablishDay: '16/06/2021 12:00:00 AM',
//     SectorID: '16',
//     SectorName: 'Media',
//     BankName: 'Saccombank',
//     BusinessTypeID: '16',
//     BusinessTypeName: 'C�ng ty c�? ph�`n',
//     IndustryID: '16',
//     IndustryName: 'Di?ch vu? cham so�c sa�c de?p',
//     CountryID: '16',
//     CountryName: 'Vi�?t Nam',
//     DistrictID: '16',
//     DistrictName: 'Huy�?n Qu��c Oai',
//     Street: '16 Ngo~ 225',
//     ProvinceID: '16',
//     ProvinceName: 'Ninh Bi`nh',
//     WardID: '16',
//     WardName: 'Qu�t L�m tu?',
//     ZipCode: '78096',
//     Description:
//       'Ut sed voluptas. Molestiae doloribus doloremque? Voluptates laudantium et. Voluptatem odio minima. Qui optio quisquam! Voluptates sed corporis. Perspiciatis.',
//     IsPublic: 'true',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
//   {
//     LeadID: '62a849b4-1145-4227-7009-bf1378b8dc91',
//     LeadCode: 'TN-5979',
//     LastName: 'L�',
//     FirstName: 'Di?m Hu?ng',
//     Email: 'qghung19@gmail.com',
//     Address: ' Ha` Nam ',
//     TitleID: '5e272913-6cff-509f-d8b8-94f47731937d',
//     TitleName: ' Truo?ng pho`ng ',
//     AnnualRevenueID: 'null',
//     AnnualRevenueName: ' 25 ty? d�`ng ',
//     SalutationID: '18',
//     SalutationName: '�ng ',
//     DepartmentID: '4782d29d-4baf-7371-d290-152dfadf6d0d',
//     DepartmentName: '\r\n Pho`ng nghi�n cu�u ',
//     Mobile: '0875393776',
//     OfficeMobile: '0331970679',
//     LeadSourceID: '18',
//     LeadSourceName: 'Kha�ch ha`ng duo?c ta?ng mi�~n phi�',
//     LeadTypeID: '18',
//     LeadTypeName: 'KH Thuong Ma?i',
//     Zalo: 'Nguy?n L?',
//     OfficeEmail: 'qghung19@gmail.com',
//     CompanyName: 'MISA JSC ',
//     TaxCode: 'null',
//     BankAccount: '8379423155',
//     EstablishDay: '03/07/2014 12:00:00 AM',
//     SectorID: '18',
//     SectorName: 'Industrial Metals & Mining',
//     BankName: 'VietComBank',
//     BusinessTypeID: '18',
//     BusinessTypeName: 'null',
//     IndustryID: '18',
//     IndustryName: '\r\nDi?ch vu? hi�u hi?',
//     CountryID: '18',
//     CountryName: 'Vi�?t Nam',
//     DistrictID: '18',
//     DistrictName: 'Huy�?n Phu�c tho?',
//     Street: '16 Ngo~ 225',
//     ProvinceID: '18',
//     ProvinceName: 'Ninh Bi`nh',
//     WardID: '18',
//     WardName: 'Qu�t L�m tu?',
//     ZipCode: '95191',
//     Description:
//       'Laborum cum praesentium est unde temporibus; tempora rem sit molestiae. Numquam illo aut inventore voluptatem rerum quidem!',
//     IsPublic: 'false',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
//   {
//     LeadID: '6b47b37f-3123-3ce7-14cf-9712082ff6cb',
//     LeadCode: 'TN-5038',
//     LastName: 'Nguy?n',
//     FirstName: 'Mai L?',
//     Email: 'nhungkiuu01@gmail.com',
//     Address: ' Ho`a Bi`nh \r\n',
//     TitleID: '5ada22d3-3248-6596-6e1a-bb545470e80c',
//     TitleName: ' Truo?ng pho`ng ',
//     AnnualRevenueID: '423d5b84-2191-6cce-df3d-c9e9e9038fe2',
//     AnnualRevenueName: '1 ty? d�`ng ',
//     SalutationID: '7',
//     SalutationName: ' Anh Chi?',
//     DepartmentID: '4958949d-17c9-454d-841b-27d9d367aeb0',
//     DepartmentName: 'Pho`ng kinh doanh ',
//     Mobile: '0876380167',
//     OfficeMobile: '0368871934',
//     LeadSourceID: '7',
//     LeadSourceName: 'Kha�ch ha`ng duo?c ta?ng mi�~n phi�',
//     LeadTypeID: '7',
//     LeadTypeName: 'KH Sa?n Xu�t',
//     Zalo: 'Nguy?n Cu?ng',
//     OfficeEmail: 'thinhutc191204033@gmail.com',
//     CompanyName: ' Solution Dev ',
//     TaxCode: 'KC66W5UYB0BY1',
//     BankAccount: '7738158730',
//     EstablishDay: '25/12/2021 12:00:00 AM',
//     SectorID: '7',
//     SectorName: 'Technology Hardware & Equipment',
//     BankName: 'Agribank',
//     BusinessTypeID: '7',
//     BusinessTypeName: 'C�ng ty TNHH',
//     IndustryID: '7',
//     IndustryName: '\r\nDi?ch vu? cung u�ng ph�`n m�`m',
//     CountryID: '7',
//     CountryName: 'Vi�?t Nam',
//     DistrictID: '7',
//     DistrictName: 'Huy�?n Qu��c Oai',
//     Street: '909 ngo~ ~507',
//     ProvinceID: '7',
//     ProvinceName: 'Ninh Bi`nh',
//     WardID: '7',
//     WardName: 'Non Bi`nh',
//     ZipCode: '11427',
//     Description:
//       'Veniam consequuntur quis a quia. Aut quo mollitia eos natus fugiat ut. Explicabo sed ut enim voluptates sit omnis.',
//     IsPublic: 'true',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
//   {
//     LeadID: '749af78e-699e-5d1e-7109-bf1378b8dc91',
//     LeadCode: 'TN-8392',
//     LastName: 'Nguy?n',
//     FirstName: 'Th? Huong',
//     Email: 'qkhai019gmail.com',
//     Address: ' Ba�c Giang ',
//     TitleID: '4e53ab23-4fbb-7431-fe4d-8601bf3d85d8',
//     TitleName: ' Truo?ng pho`ng ',
//     AnnualRevenueID: '71a5d760-185e-3522-ea36-63d5d5eff719',
//     AnnualRevenueName: ' 15 ty? d�`ng ',
//     SalutationID: '25',
//     SalutationName: ' Anh Chi?',
//     DepartmentID: '4520aa7f-492a-3c02-a066-a58ab8ff47ca',
//     DepartmentName: ' Pho`ng nh�n su? ',
//     Mobile: '0335720181',
//     OfficeMobile: '0976840250',
//     LeadSourceID: '25',
//     LeadSourceName: 'Kha�ch ha`ng duo?c ta?ng mi�~n phi�',
//     LeadTypeID: '25',
//     LeadTypeName: 'KH Sa?n Xu�t',
//     Zalo: 'Nguy?n Tu?n',
//     OfficeEmail: 'vthanh0019@gmail.com',
//     CompanyName: ' FPT Soft ',
//     TaxCode: 'V5441JXYL4DZ5',
//     BankAccount: '0329656518',
//     EstablishDay: '31/01/2012 12:00:00 AM',
//     SectorID: '25',
//     SectorName: 'Oil Equipment, Services & Distribution',
//     BankName: 'VietComBank',
//     BusinessTypeID: '25',
//     BusinessTypeName: 'C�ng ty TNHH',
//     IndustryID: '25',
//     IndustryName: '\r\nDi?ch vu? cho thu� kho ba~i',
//     CountryID: '25',
//     CountryName: 'Vi�?t Nam',
//     DistrictID: '25',
//     DistrictName: 'Huy�?n Phu�c tho?',
//     Street: '938 ngo~ ~458',
//     ProvinceID: '25',
//     ProvinceName: 'null',
//     WardID: '25',
//     WardName: 'null',
//     ZipCode: '11796',
//     Description: 'Rem ullam iste sapiente saepe voluptatem nobis.',
//     IsPublic: 'true',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
//   {
//     LeadID: '7dbd90f6-6015-12c6-4b29-a2925c0f334d',
//     LeadCode: 'TN-8126',
//     LastName: 'V�',
//     FirstName: 'Vi?t Cu?ng',
//     Email: 'ngthinh949@gmail.com',
//     Address: ' Hung Y�n ',
//     TitleID: '1e3c96c9-1471-23e0-8765-390639088226',
//     TitleName: 'Gia�m d��c ',
//     AnnualRevenueID: '4c23f8b5-378c-4c80-e23d-c9e9e9038fe2',
//     AnnualRevenueName: ' 25 ty? d�`ng ',
//     SalutationID: '22',
//     SalutationName: '�ng ',
//     DepartmentID: '193ee03f-15cd-70e7-bd7b-a3ff9b28ff75',
//     DepartmentName: ' Pho`ng truy�`n th�ng',
//     Mobile: '0366146264',
//     OfficeMobile: '0976029404',
//     LeadSourceID: '22',
//     LeadSourceName: 'Kha�ch ha`ng tu? ti`m d�n\r\n',
//     LeadTypeID: '22',
//     LeadTypeName: 'KH Thuong Ma?i',
//     Zalo: '�a?ng Loan',
//     OfficeEmail: 'qkhai019gmail.com',
//     CompanyName: ' Solution Dev ',
//     TaxCode: 'SD6312BLC9E9O',
//     BankAccount: '1030337905',
//     EstablishDay: '18/12/2013 12:00:00 AM',
//     SectorID: '22',
//     SectorName: 'Automobiles & Parts',
//     BankName: 'Agribank',
//     BusinessTypeID: '22',
//     BusinessTypeName: 'Cu?a ha`ng trung t�m',
//     IndustryID: '22',
//     IndustryName: 'Di?ch vu? cham so�c sa�c de?p',
//     CountryID: '22',
//     CountryName: 'Vi�?t Nam',
//     DistrictID: '22',
//     DistrictName: 'Huy�?n Qu��c Oai',
//     Street: '16 Ngo~ 225',
//     ProvinceID: '22',
//     ProvinceName: 'Nam �i?nh',
//     WardID: '22',
//     WardName: 'Qu�t L�m tu?',
//     ZipCode: '49673',
//     Description:
//       'Obcaecati est neque; nemo in nobis officiis. Qui velit cumque quasi non vero aliquam! Exercitationem dicta voluptatem eum aperiam quia laboriosam.',
//     IsPublic: 'true',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
//   {
//     LeadID: 'ad5eb9ee-0d70-49a1-9f7a-38b41ced8460',
//     LeadCode: 'TN-123234',
//     LastName: '�a?ng',
//     FirstName: 'Hu~u Thi?nh',
//     Email: 'thinh191204033@gmail.com',
//     Address: 'Ninh Bi`nh',
//     TitleID: '',
//     TitleName: 'null',
//     AnnualRevenueID: '',
//     AnnualRevenueName: 'null',
//     SalutationID: 'null',
//     SalutationName: 'null',
//     DepartmentID: 'null',
//     DepartmentName: 'null',
//     Mobile: '0979359018',
//     OfficeMobile: 'null',
//     LeadSourceID: 'null',
//     LeadSourceName: 'null',
//     LeadTypeID: 'null',
//     LeadTypeName: 'null',
//     Zalo: 'null',
//     OfficeEmail: 'null',
//     CompanyName: 'null',
//     TaxCode: 'null',
//     BankAccount: 'null',
//     EstablishDay: 'null',
//     SectorID: 'null',
//     SectorName: 'null',
//     BankName: 'null',
//     BusinessTypeID: 'null',
//     BusinessTypeName: 'null',
//     IndustryID: 'null',
//     IndustryName: 'null',
//     CountryID: 'null',
//     CountryName: 'null',
//     DistrictID: 'null',
//     DistrictName: 'null',
//     Street: 'null',
//     ProvinceID: 'null',
//     ProvinceName: 'null',
//     WardID: 'null',
//     WardName: 'null',
//     ZipCode: 'null',
//     Description: 'null',
//     IsPublic: 'null',
//     CreatedDate: 'null',
//     CreatedBy: 'null',
//     ModifiedDate: 'null',
//     ModifiedBy: 'null',
//   },
// ]
const LEAD_DATA = []
export default LEAD_DATA
